config/routes.rb
Rails.application.routes.draw do
  get 'featured/index'
resources :interns
resources:project_sponsors
  # get 'welcome/homepage'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'welcome#homepage'

  get 'featured' => 'project_sponsors#featured'
  
  get 'homepage' => 'welcome#homepage'

  get 'about' => 'pages#about'

  get 'sponsors' => 'pages#sponsors'

  get 'internships' => 'pages#internships'
  
  
end

app/models/project_sponsor.rb
class ProjectSponsor < ApplicationRecord
    validates :ProjectSponsorName, :ProjectName, :ProjectDesc, :ProjectScope, presence: true
end

app/controllers/project_sponsors_controller.rb
class ProjectSponsorsController < ApplicationController
  before_action :set_project_sponsor, only: [:show, :edit, :update, :destroy]

  # GET /project_sponsors
  # GET /project_sponsors.json
  def index
    @project_sponsors = ProjectSponsor.all
  end

  
  
  # GET /project_sponsors/1
  # GET /project_sponsors/1.json
  def show
  @project_sponsors = ProjectSponsor.all
  end

  # GET /project_sponsors/new
  def new
    @project_sponsor = ProjectSponsor.new
  end

  # GET /project_sponsors/1/edit
  def edit
  end

  # POST /project_sponsors
  # POST /project_sponsors.json
  def create
    @project_sponsor = ProjectSponsor.new(project_sponsor_params)

    respond_to do |format|
      if @project_sponsor.save
        format.html { redirect_to @project_sponsor, notice: 'Project sponsor was successfully created.' }
        format.json { render :show, status: :created, location: @project_sponsor }
      else
        format.html { render :new }
        format.json { render json: @project_sponsor.errors, status: :unprocessable_entity }
      end
    end
  end
  
  # PATCH/PUT /project_sponsors/1
  # PATCH/PUT /project_sponsors/1.json
  def update
    respond_to do |format|
      if @project_sponsor.update(project_sponsor_params)
        format.html { redirect_to @project_sponsor, notice: 'Project sponsor was successfully updated.' }
        format.json { render :show, status: :ok, location: @project_sponsor }
      else
        format.html { render :edit }
        format.json { render json: @project_sponsor.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /project_sponsors/1
  # DELETE /project_sponsors/1.json
  def destroy
    @project_sponsor.destroy
    respond_to do |format|
      format.html { redirect_to project_sponsors_url, notice: 'Project sponsor was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_project_sponsor
      @project_sponsor = ProjectSponsor.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def project_sponsor_params
      params.require(:project_sponsor).permit(:ProjectName, :ProjectDesc, :ProjectSponsorName, :ProjectSponsorLink, :ProjectScope, :feature)
    end
end

app/helpers/project_sponsors_helper.rb
module ProjectSponsorsHelper
end

app/views/project_sponsors/_form.html.erb
<html>
  <head>
   <style>
    body {
      background-color: #f0f0f0;
    }
    div  {
      padding-left: 80px;
    }
	.header {
	}
   </style>
  </head>
</html>

<%= form_with(model: project_sponsor, local: true) do |form| %>
  <% if project_sponsor.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(project_sponsor.errors.count, "error") %> prohibited this project_sponsor from being saved:</h2>

      <ul>
      <% project_sponsor.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

    <div class="field">
    <%= form.label :ProjectSponsorName, 'Project Sponsor Name' %>
	    <br>
    <%= form.text_field :ProjectSponsorName %>
    </div>
  
  <div class="field">
    <%= form.label :ProjectName, 'Project Name' %>
    <br>
	<%= form.text_field :ProjectName %>
  </div>

  <div class="field">
    <%= form.label :ProjectDesc, 'Project Description' %>
    <br>
	<%= form.text_area :ProjectDesc, :size =>200, :rows => "10" %>
  </div>

  <div class="field">
    <%= form.label :ProjectSponsorLink, 'Project Sponsor Webpage Link' %>
    <br>
	    <%= form.text_field :ProjectSponsorLink %>
  </div>
  
  <div class="field">
    <%= form.label :ProjectScope, 'Project Scope' %>
    <br>	
	    <%= form.select :ProjectScope, ['', 'Artificial Intelligence', 'Data Mining', 'Java Application', 'Rails Application', 'Web Application', 'Website']%>
  </div>

  <div class="field">
    <%= form.label :feature, 'Project Sponsor Webpage Link' %>
	  <%= form.check_box :feature, :style => "width: 16px; height: 16px;"%>
  </div>
  
  <div class="actions">
    <%= form.submit 'Submit Project'%>
  </div>

<% end %>

app/views/project_sponsors/edit.html.erb
<h1>Editing Project Sponsor</h1>

<%= render 'form', project_sponsor: @project_sponsor %>

<%= link_to 'Show', @project_sponsor %> |
<%= link_to 'Cancel Project', project_sponsors_path %>

app/views/project_sponsors/new.html.erb
 <html>
  <head>
   <style>
     div  {
       padding-left:80px;
     }
 	.header {
 	padding-left: 80px;
 	}
    </style>
   </head>
 </html>

<div class="header">
<h1>Sponsor a Project Form </h1>
</div>

<%= render 'form', project_sponsor: @project_sponsor %>

  <div class="actions">
    <%= link_to 'Cancel', project_sponsors_path %>
  </div>

  
  

app/views/project_sponsors/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Project Name:</strong>
  <%= @project_sponsor.ProjectName %>
</p>

<p>
  <strong>Project Description:</strong>
  <%= @project_sponsor.ProjectDesc %>
</p>

<p>
  <strong>Project Sponsor's Name:</strong>
  <%= @project_sponsor.ProjectSponsorName %>
</p>

<p>
  <strong>Project Sponsor's Webpage Link:</strong>
  <%= @project_sponsor.ProjectSponsorLink %>
</p>

<p>
  <strong>Project Scope:</strong>
  <%= @project_sponsor.ProjectScope%>
</p>

<p>
  <strong>feature:</strong>
  <%= @project_sponsor.feature %>
</p>

<%= link_to 'Edit', edit_project_sponsor_path(@project_sponsor) %> |
<%= link_to 'Back', project_sponsors_path %>