config/routes.rb
Rails.application.routes.draw do
  get 'featured/index'
resources :interns
resources:project_sponsors
  # get 'welcome/homepage'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'welcome#homepage'

  get 'featured' => 'project_sponsors#featured'
  
  get 'homepage' => 'welcome#homepage'

  get 'about' => 'pages#about'

  get 'sponsors' => 'pages#sponsors'

  get 'internships' => 'pages#internships'
  
  
end

app/models/intern.rb
class Intern < ApplicationRecord
    mount_uploader :resume, ResumeUploader 
    validates :name, :email, :school, :education, :hours, presence: true
    validates :email, format: { with: URI::MailTo::EMAIL_REGEXP } 
end

app/controllers/interns_controller.rb
class InternsController < ApplicationController
  before_action :set_intern, only: [:show, :edit, :update, :destroy]

  # GET /interns
  # GET /interns.json
  def index
    @interns = Intern.all
  end

  # GET /interns/1
  # GET /interns/1.json
  def show
  end

  # GET /interns/new
  def new
    @intern = Intern.new
  end

  # GET /interns/1/edit
  def edit
  end

  # POST /interns
  # POST /interns.json
  def create
    @intern = Intern.new(intern_params)

    respond_to do |format|
      if @intern.save
        format.html { redirect_to @intern, notice: 'Intern was successfully created.' }
        format.json { render :show, status: :created, location: @intern }
      else
        format.html { render :new }
        format.json { render json: @intern.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /interns/1
  # PATCH/PUT /interns/1.json
  def update
    respond_to do |format|
      if @intern.update(intern_params)
        format.html { redirect_to @intern, notice: 'Intern was successfully updated.' }
        format.json { render :show, status: :ok, location: @intern }
      else
        format.html { render :edit }
        format.json { render json: @intern.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /interns/1
  # DELETE /interns/1.json
  def destroy
    @intern.destroy
    respond_to do |format|
      format.html { redirect_to interns_url, notice: 'Intern was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_intern
      @intern = Intern.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def intern_params
      params.require(:intern).permit(:name, :email, :school, :education, :html, :javascript, :java, :database, :ai, :hours, :resume)
    end
end

app/helpers/interns_helper.rb
module InternsHelper
    def booleancheck(boolean)
        if(boolean == '1')
            'Yes'
        else
            'No'
        end
    end
end

app/views/interns/_form.html.erb
<html>
  <head>
   <style>
    body {
      background-color: #f0f0f0;
    }
    div  {
      padding-left: 80px;
    }
	.header {
	}
   </style>
  </head>
</html>

<%= form_with(model: intern, local: true) do |form| %>
  <% if intern.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(intern.errors.count, "error") %> prohibited this intern from being saved:</h2>

      <ul>
      <% intern.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  

  <div class="field">
    <%= form.label :name,"Full Name:" %>
      <br>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :email, "Email:" %>
      <br>
    <%= form.text_field :email %>
  </div>

  <div class="field">
    <%= form.label :school, "School:" %>
      <br>
    <%= form.text_field :school %>
  </div>

  <div class="dropdown">

    <%= form.label "Education Level" %>

    <%= form.radio_button :education, 'Freshman' %>
    <%= form.label :Freshman %>

    <%= form.radio_button :education, 'Sophomore' %>
    <%= form.label :Sophomore %>

    <%= form.radio_button :education, 'Junior' %>
    <%= form.label :Junior %>

    <%= form.radio_button :education, 'Senior' %>
    <%= form.label :Senior %>

    <%= form.radio_button :education, 'Graduate' %>
    <%= form.label :Graduate %>
    
  </div>

  <br>

  <div id="skills">
  
      <%= form.label 'Skills' %>:
      
      <%= form.check_box :html %>
      <%= form.label :HTML %>
      
      <%= form.check_box :javascript %>
      <%= form.label :JavaScript %>
    
      <%= form.check_box :java %>
      <%= form.label :Java %>

      <%= form.check_box :database %>
      <%= form.label :Database %>

      <%= form.check_box :ai %>
      <%= form.label :AI %>    

  </div>

  <br>

  <div class="field">
    <%= form.label :hours, "Hours Available" %>
    <%= form.select :hours, (8..40) %>
  </div>
  
  <div class="field">
    <%= form.label :resume,"Upload a Resume:" %>
    <%= form.file_field :resume %>
  </div>
  
  <div class="actions">
    <%= form.submit"Save" %>
  </div>

  </div>
<% end %>

app/views/interns/edit.html.erb
<h1>Editing Intern</h1>

<%= render 'form', intern: @intern %>

<%= link_to 'Show', @intern %> |
<%= link_to 'Back', interns_path %>

app/views/interns/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Interns</h1>

<table cellpadding = "10">
  <thead>

      <tr align = "justify">
        <th align ="center">Name</th>
        <td>&nbsp;&nbsp;&nbsp;&nbsp;</td>
        <th align ="center">Email</th>
        <td>&nbsp;&nbsp;&nbsp;&nbsp;</td>
        <th align ="center">School</th>
        <td>&nbsp;&nbsp;&nbsp;&nbsp;</td>
        <th align ="center">Education</th>
        <td>&nbsp;&nbsp;&nbsp;&nbsp;</td>
        <th align ="center">HTML</th>
        <td>&nbsp;&nbsp;&nbsp;&nbsp;</td>
        <th align ="center">Javascript</th>
        <td>&nbsp;&nbsp;&nbsp;&nbsp;</td>
        <th align ="center">Java</th>
        <td>&nbsp;&nbsp;&nbsp;&nbsp;</td>
        <th align ="center">Database</th>
        <td>&nbsp;&nbsp;&nbsp;&nbsp;</td>
        <th align ="center">AI</th>
        <td>&nbsp;&nbsp;&nbsp;&nbsp;</td>
        <th align ="center">Hours</th>
        <td>&nbsp;&nbsp;&nbsp;&nbsp;</td>
        <th align ="center">Resume</th>
      </tr>
  </thead>

  <tbody>
    <% @interns.each do |intern| %>
      <tr align = "justify">
        <td align ="center"><%= intern.name %></td>
        <td>&nbsp;&nbsp;&nbsp;&nbsp;</td>
        <td align ="center"><%= intern.email %></td>
        <td>&nbsp;&nbsp;&nbsp;&nbsp;</td>
        <td align ="center"><%= intern.school %></td>
        <td>&nbsp;&nbsp;&nbsp;&nbsp;</td>
        <td align ="center"><%= intern.education %></td>
        <td>&nbsp;&nbsp;&nbsp;&nbsp;</td>
        <td align ="center"><%= booleancheck(intern.html) %></td>
        <td>&nbsp;&nbsp;&nbsp;&nbsp;</td>
        <td align ="center"><%= booleancheck(intern.javascript) %></td>
        <td>&nbsp;&nbsp;&nbsp;&nbsp;</td>
        <td align ="center"><%= booleancheck(intern.java) %></td>
        <td>&nbsp;&nbsp;&nbsp;&nbsp;</td>
        <td align ="center"><%= booleancheck(intern.database) %></td>
        <td>&nbsp;&nbsp;&nbsp;&nbsp;</td>
        <td align ="center"><%= booleancheck(intern.ai) %></td>
        <td>&nbsp;&nbsp;&nbsp;&nbsp;</td>
        <td align ="center"><%= intern.hours %></td>
        <td>&nbsp;&nbsp;&nbsp;&nbsp;</td>
        <td align ="center"><%= intern.resume %></td>
        <td>&nbsp;&nbsp;&nbsp;&nbsp;</td>

        <td><%= link_to 'Show', intern %></td>
        <td><%= link_to 'Edit', edit_intern_path(intern) %></td>
        <td><%= link_to 'Destroy', intern, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Intern', new_intern_path %>

app/views/interns/new.html.erb
<html>
<head>
 <style>
   div  {
     padding-left:80px;
   }
   .header {
   padding-left: 80px;
   }
  </style>
 </head>
</html>

<div class ="header">
<h1>Register as an Intern</h1>
</div>

<%= render 'form', intern: @intern %>

<div class = "actions">
    <%= link_to 'Cancel', interns_path %>
</div>

app/views/interns/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @intern.name %>
</p>

<p>
  <strong>Email:</strong>
  <%= @intern.email %>
</p>

<p>
  <strong>School:</strong>
  <%= @intern.school %>
</p>

<p>
  <strong>Education:</strong>
  <%= @intern.education %>
</p>

<p>
  <strong>HTML:</strong>
  <%= booleancheck(@intern.html) %>
</p>

<p>
  <strong>Javascript:</strong>
  <%= booleancheck(@intern.javascript) %>
</p>

<p>
  <strong>Java:</strong>
  <%= booleancheck(@intern.java) %>
</p>

<p>
  <strong>Database:</strong>
  <%= booleancheck(@intern.database) %>
</p>

<p>
  <strong>Ai:</strong>
  <%= booleancheck(@intern.ai) %>
</p>

<p>
  <strong>Hours:</strong>
  <%= @intern.hours %>
</p>

<p>
  <strong>Resume</strong>
  <%= @intern.resume %>
</p>

<%= link_to 'Edit', edit_intern_path(@intern) %> |
<%= link_to 'Back', interns_path %>