config/routes.rb
Rails.application.routes.draw do
  get 'featured/index'
resources :interns
resources:project_sponsors
  # get 'welcome/homepage'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'welcome#homepage'

  get 'featured' => 'project_sponsors#featured'
  
  get 'homepage' => 'welcome#homepage'

  get 'about' => 'pages#about'

  get 'sponsors' => 'pages#sponsors'

  get 'internships' => 'pages#internships'
  
  
end

app/controllers/featured_controller.rb
class FeaturedController < ApplicationController
  def index
	@project_sponsors = ProjectSponsor.all
  end
end

app/helpers/featured_helper.rb
module FeaturedHelper
end

app/views/featured/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Project Sponsors</h1>

<table>
  <thead>
    <tr>
      <th>Project Name</th>
      <th>Project Description</th>
      <th>Project Sponsor's Name</th>
      <th>Project Sponsor's Webpage Link</th>
      <th>Project Scope</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @project_sponsors.each do |project_sponsor| %>
      <tr>
        <td><%= project_sponsor.ProjectName %></td>
        <td><%= project_sponsor.ProjectDesc %></td>
        <td><%= project_sponsor.ProjectSponsorName %></td>
        <td><%= project_sponsor.ProjectSponsorLink %></td>
        <td><%= project_sponsor.ProjectScope %></td>
        <td><%= link_to 'Show', project_sponsor %></td>
        <td><%= link_to 'Edit', edit_project_sponsor_path(project_sponsor) %></td>
        <td><%= link_to 'Destroy', project_sponsor, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Project Sponsor', new_project_sponsor_path %>