config/routes.rb
Rails.application.routes.draw do
  get 'featured/index'
resources :interns
resources:project_sponsors
  # get 'welcome/homepage'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'welcome#homepage'

  get 'featured' => 'project_sponsors#featured'
  
  get 'homepage' => 'welcome#homepage'

  get 'about' => 'pages#about'

  get 'sponsors' => 'pages#sponsors'

  get 'internships' => 'pages#internships'
  
  
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Internsquad</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
   
    <%= stylesheet_link_tag   'https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css' %>
    <%= stylesheet_link_tag   'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= favicon_link_tag asset_path('laptop.png') %>

    
    
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    </head>
    <body>
        <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <div class="navbar-brand">
          <i class="fa fa-laptop fa-lg"></i>
          <%= link_to "InternSquad", root_path %>
        </div>
      <button class="ml-auto navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNav">
        <ul class="navbar-nav">
          <div class ="nav-item nav-link">
            <li>
              <%= active_link_to 'Internship Information', internships_path %>
            </li>
          </div>
          <div class ="nav-item nav-link">
            <li>
              <%= active_link_to 'Sponsors Information', sponsors_path %>
            </li>
          </div>
          <div class ="nav-item nav-link">
            <li>
              <%= active_link_to 'About', about_path %>
            </li>
          </div>
        </ul>
      </div>
    </nav>
      <%= yield %>
    </body>
</html>